version: '2.2'
services:
  app:
    build: .
    environment:
      - MODE=dev
      - ELASTICSEARCH_HOST=127.0.0.1
      - ELASTICSEARCH_PORT=9200
    volumes:
      - .:/code
    depends_on:
      - elasticsearch
      - rabbitmq
    ports:
      - "9090:9090"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.1
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.1
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet

  rabbitmq:
    image: rabbitmq:3.7.8-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "8023:15672"
      - "8024:5672"

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  esnet: